spring.datasource.url=jdbc:postgresql://ep-jolly-shape-acezpzyq.sa-east-1.aws.neon.tech/rh_system?sslmode=require&schema=public"
spring.datasource.username=neondb_owner
spring.datasource.password=npg_SePb3vkxYEQ4

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true